sudo: true

language: python
python:
  - "2.7"
compiler: gcc
env:
  global: 
  - DJANGO_SETTINGS_MODULE="cloudcv17.settings"
  # Caffe
  - WITH_CUDA=false
cache:
  pip: true
  custom_install: true
before_install:
  - export PATH=/home/travis/miniconda/bin:$PATH
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install python-coveralls
- pip install flake8
- sudo apt-get update
before_script:
  - ./scripts/travis/install-dep.sh
script:
  - flake8 ./

notifications:
  email:
    on_success: change
    on_failure: always
