sudo: required

language: python
python:
  - "2.7"

compiler: gcc

env:
  global: 
  - DJANGO_SETTINGS_MODULE="cloudcv17.settings"
  - NUM_THREADS=4
  # Caffe
  - WITH_CUDA=false
  - WITH_CMAKE=false

cache:
  pip: true
  custom_install: true
  apt: true
  directories:
  - /home/travis/miniconda
  - /home/travis/miniconda2
  - /home/travis/miniconda3

before_install:
  - export SCRIPTS=./scripts/travis
  - export CONDA_DIR="/home/travis/miniconda$PYTHON_VERSION"

install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install python-coveralls
- pip install flake8
- sudo apt-get update
- sudo -E $SCRIPTS/install-caffe.sh
- sudo -E $SCRIPTS/install-opencv.sh

before_script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/cuda/lib64:$CONDA_DIR/lib
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/dep/caffe/python
  - export PATH=$CONDA_DIR/bin:$PATH

script:
  - flake8 ./

notifications:
  email:
    on_success: change
    on_failure: always
