sudo: false

language: python
python:
  - "2.7"
compiler: gcc   # for Caffe
env:
  global: DJANGO_SETTINGS_MODULE="cloudcv17.settings"
      # Make
      - NUM_THREADS=4
      # Caffe
      - WITH_CUDA=false
      - WITH_CMAKE=false
cache:
  pip: true
  custom_install: true
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install python-coveralls
- pip install flake8
before_script:
  - ./scripts/travis/cpu-worker-installation.sh
script:
  - flake8 ./

notifications:
  email:
    on_success: change
    on_failure: always
