sudo: false

language: python
python:
  - "2.7"
env:
  global: DJANGO_SETTINGS_MODULE="cloudcv17.settings"

install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install flake8

script:
  - flake8 ./

notifications:
  email:
    on_success: change
    on_failure: always
